// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class enableMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enableMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202106100625199_enableMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
